language: python
cache: pip

services:
  - docker

jobs:
  include:
    - stage: test
      script: python -m flake8 main_app
    - stage: test
      script: docker-compose up --abort-on-container-exit
    - stage: deploy
      script: skip
      deploy:
        provider: heroku
        api_key:
          secure: XnR1H6ZxmKxh44tTriy4X/GQSIWqAOrxq9OiKlZa3ISdGk1v5IBWBs+9bTxq92/rtvaGg0aHbz7m2z+oysinez9kFzJ1Vnu/6Z07YLF6/n6ZqLHQOcDgZJAGIYAtD+9ePu+JmAv67fkK1UpBd1UPp+2pkJyrZ3EwUE6URhJP0ajj7ZG/fC6TzSdPrEBStT4v0wgGDAHMuphRqkozYDlZ61ZlYPzqbNaRlybpDtFY1U96Gnrs+zUalWttatKtBeH0rJNfm4itOQarftbENITmmKnEEx/adbXD/EApXkFtkkYqXp2rm3WutObfiK3GNPGlEsyRjFevlDahAPVN8V4JJEkJeYaK67MOPNprAZaol9KCQhh5Qw2IFPiQ6wz9wnQX9IFYLpaOB+jSUxMOrjs3lJebwRD6AxhY6aMzGEssGWQgx4CRTBAkPtanz7bI855ssZ4Ucf9A9UxYzcbzZ3psEBHvEJoILTB4/vNjdO7cHyCKqSqsZEFsXHWoaQ09W1TpRJ49KkjcxtvxSGixUEWajQbAJUEKuelc4EFP8SegeLm/F2LQdmbuv+VY5rc6kteuv4zgfmpKajDbFh3gD9iVwIQLvNzb57hEsrh2l4QYfdy+G4TqO8CQG578VG0+KQLsz06Ms+tQ9Zf+6REo3E6oV0bQwUtObmu6UwwZaDzMB+g=
        app:
          master: tt-ridesharing-backend
          dev: tt-ridesharing-backend-staging

env:
  global:
  - secure: ICUASzQfYtyrRuKSae0gnVPFLJTEQ2CbgJGrAGVipkVGqajU5rW85TDXXg2dkBPae9DtD+DuoYFOPuSYxr+a/71rnvLV5mFQj03M6/V1knddjEWrh4LpdntIdmVTXr8S3DTRoB03i+uaB/Jpoguz6wlMh2cul3zOtc+SEv8SF5bVsFBaBgP5E84FUtH9DrKGMRSeBuFWJ9hd3aO4lI0egkFaN0Xi6/VIcBZMaq8o1kunsTUjO2QOezFzkyvLbO8Gq6w/Oi63DuKbQqix0cC8ZcXyL1EdluhV+GIp7UHDmRw6GkQFaZ+eV7GJlWO4VKewghWFZmIy3bCx2YOTSxTGqxlLa7qv3eMuISVGMfQAJA2NuidJgsJRYmub/5y8paTOMmDKgZUev9TWxD46j1/aShn/RWX20PIjUG+PwqKfEK1FOrT4+WbfRcV7IUXpXw9ECUWFcS+KqlOGyfxt4t1RxcSI8Ttz9DoKe3BJPnxx/UBJyWPiY7/dqCEPIWwlDZQSois7or3UCcVlVZTVua5XmU8rIGoQUtG5WZRodo/RYfV/FWLdl3QV3+0eM1qbXTkMtSh2pVAN23RlYHOrymXJMvtu849Bcg3Ngp+mwsaP2Lvf0P9U4B/5xYnFIHhYUFoZTBo4RiwZNDfVpXrRL+rjuk8HPNc/i+0AmhCE72ov788=
  - secure: R3ZSI16SZQ5PpmqqmYYjvWRKw5bgr+K9AA1CI/ZtKhlNXCmwjs7Qzfp+JoEPRT9bn6K/cUtqC1JXVAIxf841TZlD1F7z75EyXm4eKbazW1XYRhR4xg9ixkaT+nqToBjwcMvSdlJguuJ4q3ROmMGrc9Z3sjw1zYiPYENd8iM//0vrynRbXN41yYAfpA3vhjH4ByL4qlGqN2QclzdM241AFfzO8sQUDOsKVIsn3dQ1wJhnH/kDdof0uIc0qOmif4EbFJkpWCidUogq0sEvnMJqPxp+16X5X2JoSVq70jo5eDA1wIMHeRfG8c0/WobARx5bFCL6ksId3nBaDFl6xYiasdvAILReMFoGgl+XJ+BbMzRHo9gWK8KKShAO/a2pKmUMrOJc0CIzvj8lnvphHiCjq4Tn8gc3hkdAQxihFByNeXLRzBAekbpqNIPYifIr9DPsksUxEQz2qO3jwVmhH0iikk7gRnyISO3jgEGraoCWC7QJkEte+7GHKdHDGf7fYuMU0345xrZquLl82tay54K6/A3xpw2zSbnx7mHUP5f9ynMaROFe7wqBCeBpKNT5ihdiv19nnEud7OPAdJ1GtPeB5+tEnYoKAZz85RkTiLKHWsQSmPVs0nEUFO+Lg4+JLa8RdF6/E4GOMvcKcbBdLIw+xdR1sWVxYHEpHKJ1pCuMO+8=
