language: python
cache: pip

services:
  - docker

script:
  - export SECRET_KEY=$SECRET_KEY
  - export GEOCODING_KEY=$GEOCODING_KEY
  - docker-compose -f docker-compose.test.yml up --build --abort-on-container-exit

deploy:
  provider: heroku
  on:
    all_branches: true
  api_key:
    secure: X7tB00aYB14fctluO+rsYj2X7kBbycHd92u/nFn1CRxJyaXUlAZosWISCqy52l7c8+ONBAd1p0gRnGyodBYxNIBThmlP9aAfWbDxyXMNMRkemyw6UslSTmOPabndK8OTTYei7fnRXIj7HrBwmfQcAJ4YD1/BGy/QkNKFfeM/5jMGvSFx+e4FN6gd0vMXgBNPYyI9Yjt3c2XPtPv4b7Hoo2dgsSwQmewnYaksCxcatY6dasnzWx8pXf23qLYjknPx+99SW5NL3u5V7l4gl1M98HP8gzn2tcqeHRuWLQCNhddeRtV2/5Qixsk0qgnQMvFLPePqj6LAPMh2fYAcxHAwBYilBEgW25GwGqsqZYbfCzgiGw/LPeeP8knJaOXPT/+PqdBq3iLa+xUKfVRBrcXpEhAe0wpDHwPm2kkutLCcON59NCnzpYKQmZJw30OuANz1vFjb2UWMRT3YihkAT4ZF8tGYgTlXSuKHP2KHr5ENKLqj4iMAGXmFMKMqR36pbFDeTmM+tovLCc5zkB560td+/3p7OJ+q3j8V+HV7mt5WCE53YCYGTiBXe0aUvlHpgsOfM2nFY2/Zs98ICERIvRBx/s2biZk0yo42mwaNKrksMGcbjkADKTCiIqO8zcwuxS7bLyqwPmV/6p43VsdaB51zImCc63yFczRIu7B1qdohTw0=
