language: python

services:
  - docker

script: docker-compose -f docker-compose.test.yml up --build --abort-on-container-exit

deploy:
  provider: script
  script: bash deploy.sh
  on:
    all_branches: true
