language: python
cache: pip

services:
  - docker

jobs:
  include:
    - stage: test
      script: python -m flake8 main_app
    - stage: test
      script: docker-compose -f docker-compose.test.yml up --build --abort-on-container-exit
    - stage: deploy
      script: skip
      deploy:
        provider: heroku
        api_key:
          secure: X7tB00aYB14fctluO+rsYj2X7kBbycHd92u/nFn1CRxJyaXUlAZosWISCqy52l7c8+ONBAd1p0gRnGyodBYxNIBThmlP9aAfWbDxyXMNMRkemyw6UslSTmOPabndK8OTTYei7fnRXIj7HrBwmfQcAJ4YD1/BGy/QkNKFfeM/5jMGvSFx+e4FN6gd0vMXgBNPYyI9Yjt3c2XPtPv4b7Hoo2dgsSwQmewnYaksCxcatY6dasnzWx8pXf23qLYjknPx+99SW5NL3u5V7l4gl1M98HP8gzn2tcqeHRuWLQCNhddeRtV2/5Qixsk0qgnQMvFLPePqj6LAPMh2fYAcxHAwBYilBEgW25GwGqsqZYbfCzgiGw/LPeeP8knJaOXPT/+PqdBq3iLa+xUKfVRBrcXpEhAe0wpDHwPm2kkutLCcON59NCnzpYKQmZJw30OuANz1vFjb2UWMRT3YihkAT4ZF8tGYgTlXSuKHP2KHr5ENKLqj4iMAGXmFMKMqR36pbFDeTmM+tovLCc5zkB560td+/3p7OJ+q3j8V+HV7mt5WCE53YCYGTiBXe0aUvlHpgsOfM2nFY2/Zs98ICERIvRBx/s2biZk0yo42mwaNKrksMGcbjkADKTCiIqO8zcwuxS7bLyqwPmV/6p43VsdaB51zImCc63yFczRIu7B1qdohTw0=
        app:
          master: tt-ridesharing-backend
          dev: tt-ridesharing-backend-staging

env:
  global:
  - secure: ICUASzQfYtyrRuKSae0gnVPFLJTEQ2CbgJGrAGVipkVGqajU5rW85TDXXg2dkBPae9DtD+DuoYFOPuSYxr+a/71rnvLV5mFQj03M6/V1knddjEWrh4LpdntIdmVTXr8S3DTRoB03i+uaB/Jpoguz6wlMh2cul3zOtc+SEv8SF5bVsFBaBgP5E84FUtH9DrKGMRSeBuFWJ9hd3aO4lI0egkFaN0Xi6/VIcBZMaq8o1kunsTUjO2QOezFzkyvLbO8Gq6w/Oi63DuKbQqix0cC8ZcXyL1EdluhV+GIp7UHDmRw6GkQFaZ+eV7GJlWO4VKewghWFZmIy3bCx2YOTSxTGqxlLa7qv3eMuISVGMfQAJA2NuidJgsJRYmub/5y8paTOMmDKgZUev9TWxD46j1/aShn/RWX20PIjUG+PwqKfEK1FOrT4+WbfRcV7IUXpXw9ECUWFcS+KqlOGyfxt4t1RxcSI8Ttz9DoKe3BJPnxx/UBJyWPiY7/dqCEPIWwlDZQSois7or3UCcVlVZTVua5XmU8rIGoQUtG5WZRodo/RYfV/FWLdl3QV3+0eM1qbXTkMtSh2pVAN23RlYHOrymXJMvtu849Bcg3Ngp+mwsaP2Lvf0P9U4B/5xYnFIHhYUFoZTBo4RiwZNDfVpXrRL+rjuk8HPNc/i+0AmhCE72ov788=
  - secure: R3ZSI16SZQ5PpmqqmYYjvWRKw5bgr+K9AA1CI/ZtKhlNXCmwjs7Qzfp+JoEPRT9bn6K/cUtqC1JXVAIxf841TZlD1F7z75EyXm4eKbazW1XYRhR4xg9ixkaT+nqToBjwcMvSdlJguuJ4q3ROmMGrc9Z3sjw1zYiPYENd8iM//0vrynRbXN41yYAfpA3vhjH4ByL4qlGqN2QclzdM241AFfzO8sQUDOsKVIsn3dQ1wJhnH/kDdof0uIc0qOmif4EbFJkpWCidUogq0sEvnMJqPxp+16X5X2JoSVq70jo5eDA1wIMHeRfG8c0/WobARx5bFCL6ksId3nBaDFl6xYiasdvAILReMFoGgl+XJ+BbMzRHo9gWK8KKShAO/a2pKmUMrOJc0CIzvj8lnvphHiCjq4Tn8gc3hkdAQxihFByNeXLRzBAekbpqNIPYifIr9DPsksUxEQz2qO3jwVmhH0iikk7gRnyISO3jgEGraoCWC7QJkEte+7GHKdHDGf7fYuMU0345xrZquLl82tay54K6/A3xpw2zSbnx7mHUP5f9ynMaROFe7wqBCeBpKNT5ihdiv19nnEud7OPAdJ1GtPeB5+tEnYoKAZz85RkTiLKHWsQSmPVs0nEUFO+Lg4+JLa8RdF6/E4GOMvcKcbBdLIw+xdR1sWVxYHEpHKJ1pCuMO+8=
