version: '3'

services:
  web:
    build: .
    environment:
        #- SECRET_KEY=$SECRET_KEY
        #- GEOCODING_KEY=$GEOCODING_KEY
      - DATABASE_URL=postgresql://app:app@db:5432/ridesharing
      - ELASTICSEARCH_URL=http://es:9200/
      - FLASK_RUN_HOST=0.0.0.0
    entrypoint: ["./wait-for-it.sh", "es:9200", "--", "./entrypoint.sh"]
    command: ["gunicorn", "-b", "0.0.0.0:8000", "app:create_app()"]
    ports:
        - 80:8000
    volumes:
        - ./:/app
    depends_on:
      - db
      - es

  db:
    image: postgres:latest
    ports:
    - 5432:5432
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=ridesharing
    volumes:
      - pgdata:/var/lib/postgresql/data


  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.0
    container_name: es
    environment:
      - cluster.name=es-ridesharing-docker-cluster
      - cluster.initial_master_nodes=es
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    # networks:
      # - elastic
      # - host

volumes:
  es_data01:
    driver: local
  pgdata:
    driver: local
