version: '3.7'

services:
  web:
    build: .
    env_file:
      - .env
    ports:
      - 5000:5000
    command: gunicorn --bind 0.0.0.0:5000 'app:create_app()'
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
    - postgres_data:/var/lib/postgresql/data/
    ports:
    - 5432:5432
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=ridesharing

volumes:
  postgres_data:
