"""empty message

Revision ID: 015c71bba2f1
Revises: 64274d869676
Create Date: 2019-11-01 01:40:21.025701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '015c71bba2f1'
down_revision = '64274d869676'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('address', sa.String(length=600), nullable=True))
    op.add_column('organization', sa.Column('description', sa.String(length=600), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization', 'description')
    op.drop_column('organization', 'address')
    # ### end Alembic commands ###
