"""empty message

Revision ID: 04191bd734be
Revises: dbf3c53d64ed
Create Date: 2019-10-29 12:58:52.214256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04191bd734be'
down_revision = 'dbf3c53d64ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ride', sa.Column('description', sa.String(length=600), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ride', 'description')
    # ### end Alembic commands ###
