"""empty message

Revision ID: 0f031e6b4583
Revises: 
Create Date: 2019-10-20 16:40:53.153879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f031e6b4583'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=40), nullable=False),
    sa.Column('last_name', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('photo', sa.String(length=2000), nullable=True),
    sa.Column('password_hash', sa.String(length=94), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('driver',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('passport_1', sa.String(length=2000), nullable=False),
    sa.Column('passport_2', sa.String(length=2000), nullable=False),
    sa.Column('passport_selfie', sa.String(length=2000), nullable=False),
    sa.Column('driver_license_1', sa.String(length=2000), nullable=False),
    sa.Column('driver_license_2', sa.String(length=2000), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ride',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_organization_id', sa.Integer(), nullable=False),
    sa.Column('stop_organization_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=False),
    sa.Column('host_driver_id', sa.Integer(), nullable=False),
    sa.Column('estimated_time', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['host_driver_id'], ['driver.id'], ),
    sa.ForeignKeyConstraint(['start_organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['stop_organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('association_user_ride',
    sa.Column('left_id', sa.Integer(), nullable=True),
    sa.Column('right_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['left_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['right_id'], ['ride.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association_user_ride')
    op.drop_table('ride')
    op.drop_table('driver')
    op.drop_table('users')
    op.drop_table('organization')
    # ### end Alembic commands ###
