"""empty message

Revision ID: 17fc5a54cd7d
Revises: d31660d2e1ac
Create Date: 2020-03-31 13:54:01.079678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17fc5a54cd7d'
down_revision = 'd31660d2e1ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ridefeedback', sa.Column('voter_id', sa.Integer(), server_default='1', nullable=False))
    op.create_foreign_key(op.f('fk_ridefeedback_voter_id_user'), 'ridefeedback', 'user', ['voter_id'], ['id'])
    op.add_column('userfeedback', sa.Column('voter_id', sa.Integer(), server_default='1', nullable=False))
    op.create_foreign_key(op.f('fk_userfeedback_voter_id_user'), 'userfeedback', 'user', ['voter_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_userfeedback_voter_id_user'), 'userfeedback', type_='foreignkey')
    op.drop_column('userfeedback', 'voter_id')
    op.drop_constraint(op.f('fk_ridefeedback_voter_id_user'), 'ridefeedback', type_='foreignkey')
    op.drop_column('ridefeedback', 'voter_id')
    # ### end Alembic commands ###
