"""empty message

Revision ID: 1b0a9803917e
Revises: 62a2efca73e4
Create Date: 2020-03-25 18:44:18.010779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b0a9803917e'
down_revision = '62a2efca73e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ride', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ride', 'is_active')
    # ### end Alembic commands ###
