"""empty message

Revision ID: 300c955a9b50
Revises: 4681acd2e74b
Create Date: 2019-11-11 22:37:53.977145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '300c955a9b50'
down_revision = '4681acd2e74b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organization', 'name',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organization', 'name',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###
