"""empty message

Revision ID: 334b4bb056a9
Revises: 6c9de84aa35f
Create Date: 2020-03-18 16:43:55.424631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '334b4bb056a9'
down_revision = '6c9de84aa35f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', '_password_hash',
               existing_type=sa.VARCHAR(length=94),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', '_password_hash',
               existing_type=sa.VARCHAR(length=94),
               nullable=True)
    # ### end Alembic commands ###
