"""empty message

Revision ID: 45097cd7b350
Revises: 0f031e6b4583
Create Date: 2019-10-25 11:34:55.557712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45097cd7b350'
down_revision = '0f031e6b4583'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ride', sa.Column('is_available', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ride', 'is_available')
    # ### end Alembic commands ###
