"""empty message

Revision ID: 4681acd2e74b
Revises: 9e2407a610ed
Create Date: 2019-11-10 19:08:31.062846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4681acd2e74b'
down_revision = '9e2407a610ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ride', sa.Column('car_id', sa.Integer(), server_default='2', nullable=False))
    op.create_foreign_key(None, 'ride', 'car', ['car_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ride', type_='foreignkey')
    op.drop_column('ride', 'car_id')
    # ### end Alembic commands ###
