"""empty message

Revision ID: 468486c5fbf5
Revises: a3469bd20de8
Create Date: 2019-10-30 00:40:30.381452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '468486c5fbf5'
down_revision = 'a3469bd20de8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ride', sa.Column('total_seats', sa.Integer(), server_default='4', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ride', 'total_seats')
    # ### end Alembic commands ###
