"""empty message

Revision ID: 4e968ccbe3dc
Revises: 70d6fca3c4a0
Create Date: 2019-10-20 14:58:59.430891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e968ccbe3dc'
down_revision = '70d6fca3c4a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ride_passengers_id_fkey', 'ride', type_='foreignkey')
    op.drop_column('ride', 'passengers_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ride', sa.Column('passengers_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('ride_passengers_id_fkey', 'ride', 'users', ['passengers_id'], ['id'])
    # ### end Alembic commands ###
