"""empty message

Revision ID: 62a2efca73e4
Revises: 64fc14e235d1
Create Date: 2020-03-25 17:19:00.774454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62a2efca73e4'
down_revision = '64fc14e235d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('join_ride_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('ride_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['ride_id'], ['ride.id'], name=op.f('fk_join_ride_request_ride_id_ride')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_join_ride_request_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_join_ride_request'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('join_ride_request')
    # ### end Alembic commands ###
