"""empty message

Revision ID: 64274d869676
Revises: 92abd1bd6dca
Create Date: 2019-10-30 16:41:19.567416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64274d869676'
down_revision = '92abd1bd6dca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ride', sa.Column('stop_address', sa.String(length=600), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ride', 'stop_address')
    # ### end Alembic commands ###
