"""empty message

Revision ID: 64fc14e235d1
Revises: 095161c22ab5
Create Date: 2020-03-22 21:39:37.937288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64fc14e235d1'
down_revision = '095161c22ab5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_association_user_organization_left_id_user', 'association_user_organization', type_='foreignkey')
    op.create_foreign_key(op.f('fk_association_user_organization_left_id_user'), 'association_user_organization', 'user', ['left_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_association_user_organization_left_id_user'), 'association_user_organization', type_='foreignkey')
    op.create_foreign_key('fk_association_user_organization_left_id_user', 'association_user_organization', 'user', ['left_id'], ['id'])
    # ### end Alembic commands ###
