"""add_firebaseIds_table

Revision ID: 7155b49f8c80
Revises: 30f075da28c6
Create Date: 2020-06-14 19:10:47.824971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7155b49f8c80'
down_revision = '30f075da28c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firebase_ids',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('firebase_id', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_firebase_ids_user_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_firebase_ids'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('firebase_ids')
    # ### end Alembic commands ###
