"""empty message

Revision ID: 8ac74dd7633c
Revises: 9a4e0ae5e050
Create Date: 2020-09-01 17:18:24.386350

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ac74dd7633c'
down_revision = '9a4e0ae5e050'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=256),
               nullable=True)
    op.create_unique_constraint(op.f('uq_user_phone_number'), 'user', ['phone_number'])
    op.drop_constraint('uq_user_email', 'user', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_user_email', 'user', ['email'])
    op.drop_constraint(op.f('uq_user_phone_number'), 'user', type_='unique')
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(length=256),
               nullable=False)
    # ### end Alembic commands ###
