"""empty message

Revision ID: 91f52796cfc0
Revises: a56fe5c76e57
Create Date: 2020-03-22 17:54:31.939523

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '91f52796cfc0'
down_revision = 'a56fe5c76e57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('control_answer', sa.String(length=200), nullable=False,
                                            server_default='undefined'))
    op.add_column('organization', sa.Column('control_question', sa.String(length=400), nullable=False,
                                            server_default='undefined'))
    op.alter_column('organization', 'latitude',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('organization', 'longitude',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('organization', 'longitude',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('organization', 'latitude',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.drop_column('organization', 'control_question')
    op.drop_column('organization', 'control_answer')
    # ### end Alembic commands ###
