"""empty message

Revision ID: 92abd1bd6dca
Revises: 468486c5fbf5
Create Date: 2019-10-30 00:48:32.875634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92abd1bd6dca'
down_revision = '468486c5fbf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ride', sa.Column('cost', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ride', 'cost')
    # ### end Alembic commands ###
