"""add_driver_subscription_model

Revision ID: 9a4e0ae5e050
Revises: 7155b49f8c80
Create Date: 2020-06-17 20:01:40.801954

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a4e0ae5e050'
down_revision = '7155b49f8c80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver_subscription',
    sa.Column('subscriber_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['user.id'], name=op.f('fk_driver_subscription_driver_id_user'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subscriber_id'], ['user.id'], name=op.f('fk_driver_subscription_subscriber_id_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('subscriber_id', 'driver_id', name=op.f('pk_driver_subscription'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('driver_subscription')
    # ### end Alembic commands ###
