"""empty message

Revision ID: a56fe5c76e57
Revises: 6ef299380035
Create Date: 2020-03-22 16:46:16.067920

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a56fe5c76e57'
down_revision = '6ef299380035'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ride', sa.Column('submit_datetime', sa.DateTime(), server_default='2020-03-22T16:46:15.715457', nullable=True))
    op.drop_column('ride', 'submit_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ride', sa.Column('submit_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('ride', 'submit_datetime')
    # ### end Alembic commands ###
