"""empty message

Revision ID: af80fd67c0a9
Revises: e6ff7c3fdfbf
Create Date: 2020-03-26 14:52:29.516696

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af80fd67c0a9'
down_revision = 'e6ff7c3fdfbf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('join_ride_request', sa.Column('decline_reason', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('join_ride_request', 'decline_reason')
    # ### end Alembic commands ###
