"""empty message

Revision ID: b2546ed1e7e5
Revises: af80fd67c0a9
Create Date: 2020-03-29 15:41:49.304520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2546ed1e7e5'
down_revision = 'af80fd67c0a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_association_user_organization_right_id_organization', 'association_user_organization', type_='foreignkey')
    op.create_foreign_key(op.f('fk_association_user_organization_right_id_organization'), 'association_user_organization', 'organization', ['right_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_association_user_organization_right_id_organization'), 'association_user_organization', type_='foreignkey')
    op.create_foreign_key('fk_association_user_organization_right_id_organization', 'association_user_organization', 'organization', ['right_id'], ['id'])
    # ### end Alembic commands ###
