"""empty message

Revision ID: ba22a93700b3
Revises: cd823d72ce30
Create Date: 2019-09-28 18:32:38.987592

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ba22a93700b3'
down_revision = 'cd823d72ce30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('driver',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('passport_1', sa.String(length=2000), nullable=True),
    sa.Column('passport_2', sa.String(length=2000), nullable=True),
    sa.Column('passport_selfie', sa.String(length=2000), nullable=True),
    sa.Column('driver_license_1', sa.String(length=2000), nullable=True),
    sa.Column('driver_license_2', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('is_trusful', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('photo', sa.String(length=2000), nullable=True))
    op.drop_column('user', 'photo_url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('photo_url', mysql.VARCHAR(length=2000), nullable=True))
    op.drop_column('user', 'photo')
    op.drop_column('user', 'is_trusful')
    op.drop_table('driver')
    # ### end Alembic commands ###
