"""empty message

Revision ID: d31660d2e1ac
Revises: b2546ed1e7e5
Create Date: 2020-03-29 16:13:20.722745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd31660d2e1ac'
down_revision = 'b2546ed1e7e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userfeedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=600), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_userfeedback_user_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_userfeedback'))
    )
    op.create_table('ridefeedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rate', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=600), nullable=True),
    sa.Column('ride_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ride_id'], ['ride.id'], name=op.f('fk_ridefeedback_ride_id_ride')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ridefeedback'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ridefeedback')
    op.drop_table('userfeedback')
    # ### end Alembic commands ###
