"""empty message

Revision ID: dbf3c53d64ed
Revises: 45097cd7b350
Create Date: 2019-10-26 17:21:59.670572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbf3c53d64ed'
down_revision = '45097cd7b350'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('association_user_organization',
    sa.Column('left_id', sa.Integer(), nullable=True),
    sa.Column('right_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['left_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['right_id'], ['organization.id'], )
    )
    op.add_column('ride', sa.Column('stop_latitude', sa.Float(), nullable=False))
    op.add_column('ride', sa.Column('stop_longitude', sa.Float(), nullable=False))
    op.drop_constraint('ride_stop_organization_id_fkey', 'ride', type_='foreignkey')
    op.drop_column('ride', 'stop_organization_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ride', sa.Column('stop_organization_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('ride_stop_organization_id_fkey', 'ride', 'organization', ['stop_organization_id'], ['id'])
    op.drop_column('ride', 'stop_longitude')
    op.drop_column('ride', 'stop_latitude')
    op.drop_table('association_user_organization')
    # ### end Alembic commands ###
