"""empty message

Revision ID: df345f85a645
Revises: 
Create Date: 2020-03-22 15:03:54.268896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df345f85a645'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=40), nullable=False),
    sa.Column('last_name', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=256), nullable=False),
    sa.Column('photo_url', sa.String(length=2000), nullable=True),
    sa.Column('phone_number', sa.String(length=20), server_default='+71111111111', nullable=False),
    sa.Column('_password_hash', sa.String(length=94), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user')),
    sa.UniqueConstraint('email', name=op.f('uq_user_email'))
    )
    op.create_table('car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=100), nullable=False),
    sa.Column('color', sa.String(length=100), nullable=False),
    sa.Column('registry_number', sa.String(length=20), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], name=op.f('fk_car_owner_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_car'))
    )
    op.create_table('organization',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('address', sa.String(length=600), nullable=True),
    sa.Column('description', sa.String(length=600), nullable=True),
    sa.Column('creator_id', sa.Integer(), server_default='1', nullable=False),
    sa.Column('photo_url', sa.String(length=2000), nullable=True),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], name=op.f('fk_organization_creator_id_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organization'))
    )
    op.create_table('association_user_organization',
    sa.Column('left_id', sa.Integer(), nullable=True),
    sa.Column('right_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['left_id'], ['user.id'], name=op.f('fk_association_user_organization_left_id_user')),
    sa.ForeignKeyConstraint(['right_id'], ['organization.id'], name=op.f('fk_association_user_organization_right_id_organization'))
    )
    op.create_table('ride',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_organization_id', sa.Integer(), nullable=False),
    sa.Column('stop_latitude', sa.Float(), nullable=False),
    sa.Column('stop_longitude', sa.Float(), nullable=False),
    sa.Column('total_seats', sa.Integer(), server_default='4', nullable=False),
    sa.Column('host_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('car_id', sa.Integer(), server_default='2', nullable=False),
    sa.Column('description', sa.String(length=600), nullable=True),
    sa.ForeignKeyConstraint(['car_id'], ['car.id'], name=op.f('fk_ride_car_id_car')),
    sa.ForeignKeyConstraint(['host_id'], ['user.id'], name=op.f('fk_ride_host_id_user')),
    sa.ForeignKeyConstraint(['start_organization_id'], ['organization.id'], name=op.f('fk_ride_start_organization_id_organization')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ride'))
    )
    op.create_table('association_user_ride',
    sa.Column('left_id', sa.Integer(), nullable=True),
    sa.Column('right_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['left_id'], ['user.id'], name=op.f('fk_association_user_ride_left_id_user')),
    sa.ForeignKeyConstraint(['right_id'], ['ride.id'], name=op.f('fk_association_user_ride_right_id_ride'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('association_user_ride')
    op.drop_table('ride')
    op.drop_table('association_user_organization')
    op.drop_table('organization')
    op.drop_table('car')
    op.drop_table('user')
    # ### end Alembic commands ###
