"""empty message

Revision ID: e6ff7c3fdfbf
Revises: 956b6b2bc57d
Create Date: 2020-03-26 13:46:50.485541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6ff7c3fdfbf'
down_revision = '956b6b2bc57d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('join_ride_request', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('join_ride_request', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    # ### end Alembic commands ###
