"""empty message

Revision ID: f7c64f79678f
Revises: 10476192d486
Create Date: 2019-11-05 20:15:18.216185

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7c64f79678f'
down_revision = '10476192d486'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver', sa.Column('license_1', sa.String(length=2000), server_default='', nullable=False))
    op.add_column('driver', sa.Column('license_2', sa.String(length=2000), server_default='', nullable=False))
    op.drop_column('driver', 'driver_license_1')
    op.drop_column('driver', 'driver_license_2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver', sa.Column('driver_license_2', sa.VARCHAR(length=2000), autoincrement=False, nullable=False))
    op.add_column('driver', sa.Column('driver_license_1', sa.VARCHAR(length=2000), autoincrement=False, nullable=False))
    op.drop_column('driver', 'license_2')
    op.drop_column('driver', 'license_1')
    # ### end Alembic commands ###
